{{- if .Values.rabbitmq.enabled }}
{{- /* Create secret for RabbitMQ in format expected by Bitnami chart */}}
{{- $secretName := printf "%s-rabbitmq" (include "tatarlang-chart.fullname" .) }}
{{- /* Set the secret name in values for subchart */}}
{{- $_ := set .Values.rabbitmq.auth "existingPasswordSecret" $secretName }}
{{- if .Values.vault.enabled }}
{{- $rabbitmqUser := .Values.vault.refs.rabbitmq.user }}
{{- $rabbitmqPass := .Values.vault.refs.rabbitmq.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  rabbitmq-password: {{ $rabbitmqPass | quote }}
  rabbitmq-username: {{ $rabbitmqUser | quote }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | quote }}
  rabbitmq-username: {{ .Values.secrets.rabbitmq.user | quote }}
{{- end }}
{{- end }}

