{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-db-secret
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-rabbitmq-secret
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_USER: {{ .Values.secrets.rabbitmq.user | quote }}
  RABBITMQ_PASS: {{ .Values.secrets.rabbitmq.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-celery-secret
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  CELERY_BROKER_URL: {{ .Values.secrets.celery.brokerUrl | quote }}
{{- else }}
{{- /* When vault is enabled, secrets are retrieved from Vault using vals */}}
{{- /* This template will be processed by helm-secrets which uses vals to resolve vault refs */}}
{{- $postgresUser := .Values.vault.refs.postgres.user }}
{{- $postgresPassword := .Values.vault.refs.postgres.password }}
{{- $rabbitmqUser := .Values.vault.refs.rabbitmq.user }}
{{- $rabbitmqPass := .Values.vault.refs.rabbitmq.password }}
{{- $celeryBrokerUrl := .Values.vault.refs.celery.brokerUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-db-secret
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ $postgresUser | quote }}
  POSTGRES_PASSWORD: {{ $postgresPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-rabbitmq-secret
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_USER: {{ $rabbitmqUser | quote }}
  RABBITMQ_PASS: {{ $rabbitmqPass | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatarlang-chart.fullname" . }}-celery-secret
  namespace: {{ include "tatarlang-chart.namespace" . }}
  labels:
    {{- include "tatarlang-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  CELERY_BROKER_URL: {{ $celeryBrokerUrl | quote }}
{{- end }}

