apiVersion: v2
name: tatarlang-chart
description: A Helm chart for Tatarlang application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - tatarlang
  - django
  - react
maintainers:
  - name: Tatarlang Team
# Note: Subcharts are located in charts/ directory
# They can be used as dependencies or as standalone charts

dependencies:
  - name: postgresql
    version: 0.1.0
    repository: "file://charts/postgresql"
    condition: postgresql.enabled
  - name: rabbitmq
    version: 0.1.0
    repository: "file://charts/rabbitmq"
    condition: rabbitmq.enabled

